EN = {
    "app_title": "INVAXION Patch Tool - GamerNoTitle",
    "copyright": "Copyright © 2025 GamerNoTitle. All rights reserved.\nINVAXION 音灵 is a registed trademark of Aquatrax.\nThe developer of this tool is not affiliated with Aquatrax.",
    "github": "Github",
    "select_directory": "Select Directory",
    "patch_all": "Patch All",
    "patch_char": "Patch Character",
    "patch_song": "Patch Song",
    "patch_theme": "Patch Theme",
    "no_directory_selected": "No Directory Selected",
    "read_success_title": "Successfully Read",
    "read_success_content": "Successfully found Song, Character, and theme data",
    "error_title": "Error",
    "error_invaxion_exe": "INVAXION.exe not found. Please ensure you have selected the game directory or that the game is installed correctly.",
    "error_invaxion_data": "INVAXION_DATA folder not found. Please ensure you have selected the game directory or that the game is installed correctly.",
    "error_streaming_assets": "StreamingAssets folder not found. Please ensure you have selected the game directory or that the game is installed correctly.",
    "warning_title": "Warning",
    "warning_empty_data": "Data for {key_name} is empty: {data_str}",
    "warning_empty_bytes": "Encoded data is empty, cannot write to {key_name}",
    "warning_partial_failure": "Partial Patch failed, please check error messages!",
    "steam": "Developer's Steam",
    "success_title": "Completed",
    "success_patch_all": "Successfully Patched Character, Song, and Starship",
    "success_patch_char": "Successfully Patched Character",
    "success_patch_song": "Successfully Patched Song",
    "success_patch_theme": "Successfully Patched Starship",
    "registry_error": "Registry write error ({key_name}): {error_msg}",
}
ZH_CN = {
    "app_title": "INVAXION 音灵全解锁补丁 - GamerNoTitle",
    "copyright": "Copyright © 2025 GamerNoTitle, 保留所有权利。\nNVAXION 音灵是 Aquatrax 的注册商标。\n本工具的开发者与 Aquatrax 无关。",
    "github": "Github",
    "select_directory": "选择游戏目录",
    "patch_all": "我全都要！",
    "patch_char": "应用补丁到角色",
    "patch_song": "应用补丁到铺面",
    "patch_theme": "应用补丁到星舰",
    "no_directory_selected": "未选择目录",
    "read_success_title": "读取成功",
    "read_success_content": "成功找到铺面、角色和星舰数据",
    "error_title": "错误",
    "error_invaxion_exe": "未找到 INVAXION.exe，请确认你选择的是游戏所在的目录或者游戏安装完整。",
    "error_invaxion_data": "未找到 INVAXION_DATA 文件夹，请确认你选择的是游戏所在的目录或者游戏安装完整。",
    "error_streaming_assets": "未找到 StreamingAssets 文件夹，请确认你选择的是游戏所在的目录或者游戏安装完整。",
    "warning_title": "警告",
    "warning_empty_data": "写入 {key_name} 的数据为空: {data_str}",
    "warning_empty_bytes": "编码后的数据为空，无法写入 {key_name}",
    "warning_partial_failure": "部分数据应用补丁失败，请检查错误信息！",
    "steam": "我的 Steam",
    "success_title": "完成",
    "success_patch_all": "成功应用补丁到角色、铺面和星舰",
    "success_patch_char": "成功应用补丁到角色",
    "success_patch_song": "成功应用补丁到铺面",
    "success_patch_theme": "成功应用补丁到星舰",
    "registry_error": "注册表写入错误 ({key_name}): {error_msg}",
}
ZH_TW = {
    "app_title": "INVAXION 音靈全解鎖補丁 - GamerNoTitle",
    "copyright": "Copyright © 2025 GamerNoTitle，保留所有權利。\nINVAXION 音靈是 Aquatrax 的註冊商標。\n本工具的開發者與 Aquatrax 無關。",
    "github": "Github",
    "select_directory": "選擇遊戲目錄",
    "patch_all": "我全都要！",
    "patch_char": "應用補丁到角色",
    "patch_song": "應用補丁到譜面",
    "patch_theme": "應用補丁到星艦",
    "no_directory_selected": "未選擇目錄",
    "read_success_title": "讀取成功",
    "read_success_content": "成功找到譜面、角色和星艦資料",
    "error_title": "錯誤",
    "error_invaxion_exe": "未找到 INVAXION.exe，請確認您選擇的是遊戲所在的目錄或遊戲安裝完整。",
    "error_invaxion_data": "未找到 INVAXION_DATA 資料夾，請確認您選擇的是遊戲所在的目錄或遊戲安裝完整。",
    "error_streaming_assets": "未找到 StreamingAssets 資料夾，請確認您選擇的是遊戲所在的目錄或遊戲安裝完整。",
    "warning_title": "警告",
    "warning_empty_data": "寫入 {key_name} 的資料為空: {data_str}",
    "warning_empty_bytes": "編碼後的資料為空，無法寫入 {key_name}",
    "warning_partial_failure": "部分資料應用補丁失敗，請檢查錯誤訊息！",
    "steam": "我的 Steam",
    "success_title": "完成",
    "success_patch_all": "成功應用補丁到角色、譜面和星艦",
    "success_patch_char": "成功應用補丁到角色",
    "success_patch_song": "成功應用補丁到譜面",
    "success_patch_theme": "成功應用補丁到星艦",
    "registry_error": "登錄檔寫入錯誤 ({key_name}): {error_msg}",
}
